#pragma once

#include "asset/Mount.h"

#include <cstdint>
#include <string>
#include <unordered_map>
#include <vector>

/// Descriptor for a single file embedded in the binary.
struct EmbeddedFile {
    const char* path;
    const uint8_t* data;
    size_t size;
};

/// Returns the compiled-in asset table (generated by EmbedAssets.cmake).
const std::vector<EmbeddedFile>& embedded_assets();

/// Mount backend that serves files embedded in the binary at compile time.
class MountEmbedded : public Mount {
  public:
    MountEmbedded();

    void load() override;
    bool seek_file(const std::string& path) const override;
    std::vector<uint8_t> fetch_data(const std::string& path) override;

  protected:
    void load_cache() override {
    }
    void save_cache() override {
    }

  private:
    std::unordered_map<std::string, const EmbeddedFile*> index_;
};
