#!/bin/bash
# Generate a Caddyfile for kagami. Output goes to stdout.
#
# Environment variables (set by deploy.sh from kagami.json):
#   CADDY_TLS           - "auto" (HTTP-01, default) or "dns" (Route53 DNS-01)
#   CADDY_OBSERVABILITY - "true" to include Grafana + Prometheus routes
#   CADDY_METRICS_ALLOW - Space-separated IPs allowed to reach /metrics (empty = unrestricted)
#   CADDY_HTTP_PORT     - kagami HTTP port (default: 8080)
#   CADDY_WS_PORT       - kagami WS port (default: 27016)
#   CADDY_WSS_PORT      - Caddy WSS listen port (default: 27015)
#
# Usage:
#   CADDY_WSS_PORT=27015 CADDY_WS_PORT=27016 ./generate-caddyfile.sh > Caddyfile

set -euo pipefail

TLS_MODE="${CADDY_TLS:-auto}"
OBSERVABILITY="${CADDY_OBSERVABILITY:-false}"
METRICS_ALLOW="${CADDY_METRICS_ALLOW:-}"
HTTP_PORT="${CADDY_HTTP_PORT:-8080}"
WS_PORT="${CADDY_WS_PORT:-27016}"
WSS_PORT="${CADDY_WSS_PORT:-27015}"

# --- Global server options ---
cat <<EOF
# Generated by generate-caddyfile.sh — do not edit by hand.
{
	servers :443 {
		timeouts {
			read_header 10s
			read_body   30s
			idle        120s
		}
	}
	servers :${WSS_PORT} {
		timeouts {
			read_header 10s
			idle        120s
		}
	}
}

EOF

# --- TLS snippet ---
if [ "$TLS_MODE" = "dns" ]; then
    cat <<'EOF'
# TLS via Route53 DNS-01 (for IPv6-only or firewalled instances)
(tls_active) {
	tls {
		dns route53
	}
}

EOF
else
    cat <<'EOF'
# TLS via automatic HTTPS (HTTP-01 / ACME default)
(tls_active) {
}

EOF
fi

# --- Main HTTPS site block ---
cat <<'EOF'
# --- HTTPS (port 443) ---
{$KAGAMI_DOMAIN} {
	import tls_active

	request_body {
		max_size 64KB
	}

EOF

# Observability routes (before catch-all)
if [ "$OBSERVABILITY" = "true" ]; then
    cat <<'EOF'
	# Grafana (served from /grafana/)
	handle /grafana* {
		reverse_proxy 127.0.0.1:3000
	}

	# Prometheus (served from /prometheus/)
	handle /prometheus* {
		reverse_proxy 127.0.0.1:9090
	}

EOF
fi

# /metrics IP restriction
if [ -n "$METRICS_ALLOW" ]; then
    cat <<EOF
	# Restrict /metrics to allowed IPs
	handle /metrics {
		@allowed remote_ip $METRICS_ALLOW
		handle @allowed {
			reverse_proxy 127.0.0.1:${HTTP_PORT}
		}
		respond "Forbidden" 403
	}

EOF
fi

# Catch-all → kagami
cat <<EOF
	# Game server API (catch-all)
	handle {
		reverse_proxy 127.0.0.1:${HTTP_PORT} {
			transport http {
				keepalive 60s
				keepalive_idle_conns 64
				max_conns_per_host 256
				read_timeout  30s
				write_timeout 30s
			}
		}
	}
}

EOF

# --- WSS block ---
cat <<EOF
# --- WebSocket / AO2 protocol (port ${WSS_PORT}, TLS) ---
{\$KAGAMI_DOMAIN}:${WSS_PORT} {
	import tls_active

	reverse_proxy 127.0.0.1:${WS_PORT} {
		transport http {
			keepalive     off
			read_timeout  120s
			write_timeout 120s
		}
	}
}
EOF
