#!/bin/bash
# Generate a Caddyfile for kagami. Output goes to stdout.
#
# Environment variables (set by deploy.sh from kagami.json):
#   CADDY_TLS           - "auto" (HTTP-01, default) or "dns" (Route53 DNS-01)
#   CADDY_OBSERVABILITY - "true" to include Grafana + Prometheus routes
#   CADDY_METRICS_ALLOW - Space-separated IPs allowed to reach /metrics (empty = unrestricted)
#   CADDY_HTTP_PORT     - kagami HTTP port (default: 8080)
#   CADDY_WS_PORT       - kagami WS port (default: 27016)
#
# Usage:
#   ./generate-caddyfile.sh > Caddyfile

set -euo pipefail

TLS_MODE="${CADDY_TLS:-auto}"
OBSERVABILITY="${CADDY_OBSERVABILITY:-false}"
METRICS_ALLOW="${CADDY_METRICS_ALLOW:-}"
HTTP_PORT="${CADDY_HTTP_PORT:-8080}"
WS_PORT="${CADDY_WS_PORT:-27016}"

# --- Global server options ---
cat <<'EOF'
# Generated by generate-caddyfile.sh — do not edit by hand.
{
	servers :443 {
		timeouts {
			read_header 10s
			read_body   30s
			idle        120s
		}
	}
}

EOF

# --- TLS snippet ---
if [ "$TLS_MODE" = "dns" ]; then
    cat <<'EOF'
# TLS via Route53 DNS-01 (for IPv6-only or firewalled instances)
(tls_active) {
	tls {
		dns route53
	}
}

EOF
else
    cat <<'EOF'
# TLS via automatic HTTPS (HTTP-01 / ACME default)
(tls_active) {
}

EOF
fi

# --- Single site block: HTTPS + WSS on :443 ---
cat <<'EOF'
{$KAGAMI_DOMAIN} {
	import tls_active

	request_body {
		max_size 64KB
	}

	# WebSocket upgrade — AO2 clients connect here via wss://domain/
	@websocket {
		header Connection *Upgrade*
		header Upgrade    websocket
	}
EOF

cat <<EOF
	handle @websocket {
		reverse_proxy 127.0.0.1:${WS_PORT}
	}

EOF

# Observability routes (before catch-all)
if [ "$OBSERVABILITY" = "true" ]; then
    cat <<'EOF'
	# Grafana (served from /grafana/)
	handle /grafana* {
		reverse_proxy 127.0.0.1:3000
	}

	# Prometheus — block public access (Grafana connects directly on localhost)
	handle /prometheus* {
		respond "Forbidden" 403
	}

EOF
fi

# /metrics IP restriction
if [ -n "$METRICS_ALLOW" ]; then
    cat <<EOF
	# Restrict /metrics to allowed IPs
	handle /metrics {
		@allowed remote_ip $METRICS_ALLOW
		handle @allowed {
			reverse_proxy 127.0.0.1:${HTTP_PORT}
		}
		respond "Forbidden" 403
	}

EOF
fi

# Catch-all → kagami HTTP API
cat <<EOF
	# Game server API (catch-all)
	handle {
		reverse_proxy 127.0.0.1:${HTTP_PORT} {
			transport http {
				keepalive 60s
				keepalive_idle_conns 64
				max_conns_per_host 256
				read_timeout  30s
				write_timeout 30s
			}
		}
	}
}

# --- HTTP :80 — WebSocket upgrades + HTTPS redirect ---
# ACME HTTP-01 challenges are handled automatically by Caddy
# before this block is reached.
http://{\$KAGAMI_DOMAIN} {
	@websocket {
		header Connection *Upgrade*
		header Upgrade    websocket
	}
	handle @websocket {
		reverse_proxy 127.0.0.1:${WS_PORT}
	}
	handle {
		redir https://{host}{uri} permanent
	}
}
EOF
