global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: kagami
    metrics_path: /metrics
    static_configs:
      - targets: ['kagami:80']
        labels:
          instance: canary
