#include "moderation/LocalClassifierLayer.h"

#include "utils/Log.h"

#include <cmath>
#include <cstring>

namespace moderation {

namespace {

// The binary weights format starts with an 8-byte magic. We match
// the leading 5 characters and then verify the remaining 3 bytes
// hold the version trailer 0x01 0x00 0x00. Splitting it this way
// makes the grep-for-magic use case in ops tooling work on the
// ASCII prefix alone.
constexpr const char kMagicPrefix[] = "KGCLF";
constexpr size_t kMagicTotalSize = 8;
constexpr uint32_t kSupportedFormatVersion = 1;

// Minimum header size before the variable-length model name:
//   magic(8) + version(4) + num_categories(4) + dim(4) + name_len(4)
constexpr size_t kHeaderFixedSize = 8 + 4 + 4 + 4 + 4;

/// Little-endian uint32 read from @p data at offset @p off. Caller
/// must already have bounds-checked.
uint32_t read_u32_le(const uint8_t* data, size_t off) {
    uint32_t v = 0;
    v |= static_cast<uint32_t>(data[off + 0]);
    v |= static_cast<uint32_t>(data[off + 1]) << 8;
    v |= static_cast<uint32_t>(data[off + 2]) << 16;
    v |= static_cast<uint32_t>(data[off + 3]) << 24;
    return v;
}

double sigmoid(double x) {
    // The "safe" form of sigmoid: avoids overflow in exp() for
    // very negative x by splitting into two cases. Standard trick.
    if (x >= 0.0) {
        const double z = std::exp(-x);
        return 1.0 / (1.0 + z);
    }
    const double z = std::exp(x);
    return z / (1.0 + z);
}

} // namespace

void LocalClassifierLayer::configure(const LocalClassifierConfig& cfg) {
    std::lock_guard lock(mu_);
    cfg_ = cfg;
}

bool LocalClassifierLayer::load_weights(const uint8_t* blob, size_t blob_size, const std::string& runtime_model_name) {
    std::lock_guard lock(mu_);
    loaded_ = false;
    weights_.clear();
    biases_.clear();
    num_categories_ = 0;
    embedding_dim_ = 0;
    model_name_.clear();

    if (blob == nullptr || blob_size < kHeaderFixedSize) {
        Log::warn("LocalClassifier: weights blob missing or too short ({} bytes, need at least {})", blob_size,
                  kHeaderFixedSize);
        return false;
    }

    // Magic prefix check. A mismatch here almost always means the
    // asset wasn't generated by scripts/train_classifier.py.
    if (std::memcmp(blob, kMagicPrefix, 5) != 0 || blob[5] != 0x01 || blob[6] != 0x00 || blob[7] != 0x00) {
        Log::warn("LocalClassifier: weights magic mismatch — not a classifier blob");
        return false;
    }

    const uint32_t version = read_u32_le(blob, 8);
    if (version != kSupportedFormatVersion) {
        Log::warn("LocalClassifier: unsupported format version {} (supported: {})", version, kSupportedFormatVersion);
        return false;
    }

    const uint32_t num_cat = read_u32_le(blob, 12);
    const uint32_t dim = read_u32_le(blob, 16);
    const uint32_t name_len = read_u32_le(blob, 20);

    // Upper bounds to prevent a malformed header from triggering
    // wild allocations. 64 categories and 4096 dims are both an
    // order of magnitude larger than anything real (we ship 8
    // categories and 384 dim) and cap the weights array at a
    // gigabyte worst case.
    if (num_cat == 0 || num_cat > 64) {
        Log::warn("LocalClassifier: num_categories out of range: {}", num_cat);
        return false;
    }
    if (dim == 0 || dim > 4096) {
        Log::warn("LocalClassifier: embedding_dim out of range: {}", dim);
        return false;
    }
    if (name_len > 512) {
        Log::warn("LocalClassifier: model_name_len too long: {}", name_len);
        return false;
    }

    const size_t weights_bytes = static_cast<size_t>(num_cat) * dim * sizeof(float);
    const size_t biases_bytes = static_cast<size_t>(num_cat) * sizeof(float);
    const size_t expected_size = kHeaderFixedSize + name_len + weights_bytes + biases_bytes;
    if (blob_size != expected_size) {
        Log::warn("LocalClassifier: blob size {} does not match header-derived size {} "
                  "(num_cat={}, dim={}, name_len={})",
                  blob_size, expected_size, num_cat, dim, name_len);
        return false;
    }

    std::string file_model_name(reinterpret_cast<const char*>(blob + kHeaderFixedSize), name_len);

    // Embedding-model compatibility check. See header for full
    // rationale. This is the single most important safety gate on
    // the loader: a mismatch here means the classifier would produce
    // silently-wrong outputs against the live embedding model, which
    // is a wrong-answer bug that'd be nearly impossible to detect
    // from metrics alone.
    //
    // kagami's HfModelFetcher appends ":specific.gguf" to repo ids
    // when pinning a specific quantization (e.g.
    // "ChristianAzinn/bge-small-en-v1.5-gguf:bge-small-en-v1.5.Q8_0.gguf").
    // The weights header only cares about the HF REPO the embeddings
    // come from — different quantizations of the same model produce
    // essentially the same vector space, and forcing a retrain on
    // every quantization change would be a pointless maintenance
    // trap. Normalize both sides by stripping everything after the
    // first ':' before comparing.
    auto strip_suffix = [](const std::string& s) -> std::string {
        auto colon = s.find(':');
        return colon == std::string::npos ? s : s.substr(0, colon);
    };
    const std::string file_repo = strip_suffix(file_model_name);
    const std::string runtime_repo = strip_suffix(runtime_model_name);
    if (!runtime_repo.empty() && file_repo != runtime_repo) {
        Log::warn("LocalClassifier: disabling — weights trained for '{}' but runtime "
                  "embedding model is '{}' (repo '{}' vs '{}'). Re-run "
                  "scripts/train_classifier.py against the current model and rebuild.",
                  file_model_name, runtime_model_name, file_repo, runtime_repo);
        return false;
    }

    // Copy the weights and biases into std::vector<float>. The blob
    // is little-endian float32, and x86_64/arm64 both use the same
    // native layout, so the copy is a memcpy without byte-swap.
    // (If we ever target a big-endian platform this will need a
    // byte-swap helper here.)
    weights_.resize(static_cast<size_t>(num_cat) * dim);
    biases_.resize(num_cat);
    const uint8_t* w_src = blob + kHeaderFixedSize + name_len;
    const uint8_t* b_src = w_src + weights_bytes;
    std::memcpy(weights_.data(), w_src, weights_bytes);
    std::memcpy(biases_.data(), b_src, biases_bytes);

    num_categories_ = static_cast<int>(num_cat);
    embedding_dim_ = static_cast<int>(dim);
    model_name_ = std::move(file_model_name);
    loaded_ = true;

    Log::info("LocalClassifier: loaded {} categories x {}-dim weights (model={})", num_categories_, embedding_dim_,
              model_name_);
    return true;
}

bool LocalClassifierLayer::is_active() const {
    std::lock_guard lock(mu_);
    return cfg_.enabled && loaded_;
}

int LocalClassifierLayer::num_categories() const {
    std::lock_guard lock(mu_);
    return num_categories_;
}

int LocalClassifierLayer::embedding_dim() const {
    std::lock_guard lock(mu_);
    return embedding_dim_;
}

const std::string& LocalClassifierLayer::model_name() const {
    std::lock_guard lock(mu_);
    return model_name_;
}

LocalClassifierResult LocalClassifierLayer::classify(const EmbeddingResult& embedding) const {
    LocalClassifierResult out;

    std::lock_guard lock(mu_);
    if (!loaded_ || !cfg_.enabled)
        return out;
    if (!embedding.ok)
        return out;
    if (static_cast<int>(embedding.vector.size()) != embedding_dim_)
        return out;

    // Per-axis logit = bias[i] + dot(weights_row_i, embedding).
    // Axis order matches the training script's KAGAMI_AXES constant.
    // See scripts/train_classifier.py for the mapping.
    out.max_confidence = 0.0;
    out.max_category_index = -1;

    const float* vec = embedding.vector.data();
    const float* wrow = weights_.data();
    for (int i = 0; i < num_categories_; ++i, wrow += embedding_dim_) {
        double logit = biases_[i];
        // Tight inner loop: cache-friendly row traversal, contiguous
        // embedding. The compiler autovectorizes this into SIMD on
        // every target we care about (SSE2 on x86_64, NEON on arm64).
        for (int j = 0; j < embedding_dim_; ++j) {
            logit += static_cast<double>(wrow[j]) * static_cast<double>(vec[j]);
        }
        const double prob = sigmoid(logit);

        // Map the category index to the kagami axis fields using
        // the canonical order from scripts/train_classifier.py:
        //   0 toxicity
        //   1 hate
        //   2 sexual
        //   3 sexual_minors
        //   4 violence
        //   5 self_harm
        //   6 visual_noise (zeroed in trained weights)
        //   7 link_risk    (zeroed in trained weights)
        switch (i) {
        case 0:
            out.scores.toxicity = prob;
            break;
        case 1:
            out.scores.hate = prob;
            break;
        case 2:
            out.scores.sexual = prob;
            break;
        case 3:
            out.scores.sexual_minors = prob;
            break;
        case 4:
            out.scores.violence = prob;
            break;
        case 5:
            out.scores.self_harm = prob;
            break;
        case 6:
            out.scores.visual_noise = prob;
            break;
        case 7:
            out.scores.link_risk = prob;
            break;
        default:
            break; // categories beyond 8 are ignored
        }

        if (prob > out.max_confidence) {
            out.max_confidence = prob;
            out.max_category_index = i;
        }
    }

    out.ran = true;
    return out;
}

} // namespace moderation
