# EmbedAssets.cmake — Generate a C++ source file embedding all files from a directory.
#
# Usage:
#   embed_assets(TARGET_VAR source_dir output_cpp)
#
# Scans source_dir recursively, generates output_cpp with:
#   - A byte array for each file
#   - An index mapping virtual paths to {data, size} pairs
#   - A public accessor: const std::vector<EmbeddedFile>& embedded_assets()

function(embed_assets TARGET_VAR source_dir output_cpp)
    file(GLOB_RECURSE _asset_files RELATIVE "${source_dir}" "${source_dir}/*")
    list(FILTER _asset_files EXCLUDE REGEX "^\\.") # skip hidden files

    set(_generated "// Auto-generated by EmbedAssets.cmake — do not edit.\n")
    string(APPEND _generated "#include \"asset/MountEmbedded.h\"\n\n")

    set(_index_entries "")
    set(_counter 0)

    foreach(_file ${_asset_files})
        file(READ "${source_dir}/${_file}" _content HEX)
        # Convert hex string to comma-separated 0xNN bytes
        string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," _hex_bytes "${_content}")

        string(APPEND _generated "static const uint8_t _asset_${_counter}[] = {${_hex_bytes}};\n")
        string(APPEND _index_entries "    {\"${_file}\", _asset_${_counter}, sizeof(_asset_${_counter})},\n")
        math(EXPR _counter "${_counter} + 1")
    endforeach()

    string(APPEND _generated "\nconst std::vector<EmbeddedFile>& embedded_assets() {\n")
    string(APPEND _generated "    static const std::vector<EmbeddedFile> files = {\n")
    string(APPEND _generated "${_index_entries}")
    string(APPEND _generated "    };\n")
    string(APPEND _generated "    return files;\n")
    string(APPEND _generated "}\n")

    file(WRITE "${output_cpp}" "${_generated}")
    set(${TARGET_VAR} "${output_cpp}" PARENT_SCOPE)
endfunction()
